Repository Harshil525/Hello-World-in-Multiple-Languages, pull requests merged in 2024-10, with the labels that each got.

#5 Create helloWorld.py
  helloWorld.py
Labels: documentation, hacktoberfest, hacktoberfest-accepted, hacktoberfest-2024

#6 Create helloWorld.cpp
  helloWorld.cpp
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2024

#8 Create helloWorld.java
  helloWorld.java
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2024

#13 Create helloWorld.go
  helloWorld.go
Labels: documentation, enhancement, hacktoberfest, hacktoberfest-accepted, hacktoberfest-2024

#12 Hello World GoLang
  hello.go
Labels: documentation, enhancement, hacktoberfest, hacktoberfest-accepted, hacktoberfest-2024

#11 Greeting in JS
  helloWorld.js
Labels: documentation, enhancement, hacktoberfest, hacktoberfest-accepted, hacktoberfest-2024

#15 Create HelloWorld.php
  HelloWorld.php
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2024

#19 Create helloWorld2.js
  helloWorld2.js
Labels: documentation, enhancement, hacktoberfest, hacktoberfest-accepted, hacktoberfest-2024

#18 Update helloWorld.py
  helloWorld.py
Labels: documentation, enhancement, hacktoberfest, hacktoberfest-accepted, hacktoberfest-2024

#24 Create HelloWorld.jsx
  HelloWorld.jsx
Labels: documentation, enhancement, hacktoberfest, hacktoberfest-accepted, hacktoberfest-2024

#25 Create hello_world.sh
  hello_world.sh
Labels: documentation, enhancement, hacktoberfest, hacktoberfest-accepted, hacktoberfest-2024

#30 Create hello_world.tsx
  hello_world.tsx
Labels: documentation, hacktoberfest, hacktoberfest-accepted, hacktoberfest-2024

#29 The Hello World program in two languages such as Erlang and scala for efficiency
  hello_world.erl
  helloworld.scala
Labels: documentation, hacktoberfest, hacktoberfest-accepted, hacktoberfest-2024

#28 Added in Perl
  helloWorld.pl
Labels: documentation, hacktoberfest, hacktoberfest-accepted, hacktoberfest-2024

#27 Print HelloWorld.asm
  HelloWorld.asm
Labels: documentation, hacktoberfest, hacktoberfest-accepted, hacktoberfest-2024

#26 Create hello_world.c#
  hello_world.c#
Labels: documentation, hacktoberfest, hacktoberfest-accepted, hacktoberfest-2024

#31 Added in Kotlin
  helloWorld.kt
Labels: documentation, hacktoberfest, hacktoberfest-accepted, hacktoberfest-2024

#33 Added in Ruby
  helloWorld.rb
Labels: documentation, hacktoberfest, hacktoberfest-accepted, hacktoberfest-2024

#32 hello_world.lua
  hello_world.lua
Labels: documentation, hacktoberfest, hacktoberfest-accepted, hacktoberfest-2024

#34 Created a hello world program in dart
  hello_world.dart
Labels: documentation, hacktoberfest, hacktoberfest-accepted, hacktoberfest-2024

#35 Fixed c# name and added hello world in D
  helloWorld.d
  hello_world.cs
Labels: documentation, hacktoberfest, hacktoberfest-accepted, hacktoberfest-2024

#36 Create HelloWorld.swift
  HelloWorld.swift
Labels: documentation, hacktoberfest, hacktoberfest-accepted, hacktoberfest-2024
